# Generated by Django 5.1.2 on 2025-09-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('cupcakes', 'Cupcakes'), ('cookies', 'Cookies'), ('wedding', 'Wedding Cakes'), ('birthday', 'Birthday Cakes'), ('delivery', 'Cake Deliveries'), ('decorating', 'Cake Decorating')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
